Repository cognitedata/neat, pull requests merged in 2025-04, with the labels that each got.

#1057 Improve the CDFMissingResourcesError
  cognite/neat/_issues/errors/_external.py
  cognite/neat/_rules/models/dms/_validation.py
Labels: risk-review-ongoing

#1073 [NEAT-868] 😇 Setup new test framework for validating DMS Rules
  cognite/neat/_rules/importers/_yaml2rules.py
  tests/data/__init__.py
  tests/data/_schema/physical_yamls/invalid_yaml.expected_issues.yaml
  tests/data/_schema/physical_yamls/invalid_yaml.yaml
  tests/tests_integration/test_api/__init__.py
  tests/tests_integration/test_api/test_validate_rules.py
Labels: risk-review-ongoing

#1081 removing unused dexpi extractor
  cognite/neat/_graph/extractors/__init__.py
  cognite/neat/_graph/extractors/_dexpi.py
  tests/tests_unit/test_graph/test_extractors/test_dexpi_extractor.py
Labels: risk-review-ongoing

#1076 [NEAT-873] 🪓 Split write and read for queries
  cognite/neat/_graph/loaders/_rdf2dms.py
  cognite/neat/_graph/queries/__init__.py
  cognite/neat/_graph/queries/_base.py
  cognite/neat/_graph/queries/_queries.py
  cognite/neat/_graph/queries/_select.py
  cognite/neat/_graph/queries/_update.py
  cognite/neat/_session/_drop.py
  cognite/neat/_session/_explore.py
  cognite/neat/_session/_prepare.py
  cognite/neat/_session/_set.py
  cognite/neat/_session/_show.py
  cognite/neat/_store/_graph_store.py
  tests/tests_unit/test_graph/test_extractors/test_asset_extractor.py
  tests/tests_unit/test_graph/test_transformers/test_asset_depth_transformer.py
  tests/tests_unit/test_graph/test_transformers/test_make_connection_on_exact_match.py
Labels: risk-review-ongoing

#1083 [NEAT-886] 👮 NeatGraphStore.transform catch issues
  cognite/neat/_store/_graph_store.py
  tests/tests_unit/test_graph/test_transformers/test_asset_depth_transformer.py
  tests/tests_unit/test_graph/test_transformers/test_asset_event_connector_transformer.py
  tests/tests_unit/test_graph/test_transformers/test_asset_file_connector_transformer.py
  tests/tests_unit/test_graph/test_transformers/test_asset_relationship_connector_transformer.py
  tests/tests_unit/test_graph/test_transformers/test_asset_sequence_connector_transformer.py
  tests/tests_unit/test_graph/test_transformers/test_asset_ts_connector_transformer.py
Labels: risk-review-ongoing

#1093 rename method from extension to expand
  cognite/neat/_session/_template.py
  tests/tests_integration/test_session/test_graph_flow.py
Labels: risk-review-ongoing

#1094 Fix template.expand NeatIssue handling
  cognite/neat/_session/_template.py
  tests/data/__init__.py
  tests/data/_schema/conceptual/broken_concepts.xlsx
  tests/tests_integration/test_session/test_graph_flow.py
Labels: risk-review-ongoing

#1095 fix inference bug
  cognite/neat/_session/_base.py
  tests/tests_integration/test_session/test_graph_flow.py
Labels: risk-review-ongoing, blocking-client

#1092 Neat 876 simpler data modeling tutorial
  docs/index.md
  docs/tutorials/data-modeling/data_model_provenance_cf350101.html
  docs/tutorials/data-modeling/figs/data-modeling-flow.png
  docs/tutorials/data-modeling/files/wind_farm_prospecting_conceptual_data_model.xlsx
  docs/tutorials/data-modeling/files/wind_farm_prospecting_conceptual_data_model_expanded.xlsx
  docs/tutorials/data-modeling/files/wind_farm_prospecting_physical_data_model.xlsx
  docs/tutorials/data-modeling/from-conceptual-to-physical-via-CDM.ipynb
  docs/tutorials/data-modeling/http_purl.org_cognite_neat_data-model_verified_logical_wind_energy_WindFarmProspecting_v1.html
  docs/tutorials/data-modeling/http_purl.org_cognite_neat_data-model_verified_logical_wind_energy_WindFarmProspecting_v1_implements.html
  docs/tutorials/data-modeling/physical-data-model.xlsx
  mkdocs.yml
Labels: risk-review-ongoing

#1096 NEAT-899 Remove template. solution_model()
  cognite/neat/_rules/transformers/_converters.py
  cognite/neat/_session/_template.py
  tests/tests_end_to_end/test_rules_flow.py
Labels: risk-review-ongoing

#1101 [NEAT-906] 🚅UV
  .github/workflows/code-quality.yaml
  .github/workflows/release.yaml
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
  uv.lock
Labels: risk-review-ongoing

#1102 [NEAT-904] 🤖 Robustify release process
  dev.py
  tests/tests_unit/test_neat_package_metadata.py
Labels: waiting-for-risk-review
