Repository cognitedata/neat, pull requests merged in 2025-09, with the labels that each got.

#1292 Removing debugging part of test
  tests/tests_integration/test_client_available.py
Labels: risk-review-ongoing, waiting-for-team

#1281 Refactoring dm adding key entities datatypes
  cognite/neat/_data_model/_constants.py
  cognite/neat/_data_model/_identifiers.py
  cognite/neat/_data_model/models/entities/__init__.py
  cognite/neat/_data_model/models/entities/_base.py
  cognite/neat/_data_model/models/entities/_data_types.py
  tests/tests_data_model/__init__.py
  tests/tests_data_model/test_models/__init__.py
  tests/tests_data_model/test_models/test_entities/__init__.py
  tests/tests_data_model/test_models/test_entities/test_base_entities.py
  tests/tests_data_model/test_models/test_entities/test_data_type.py
Labels: risk-review-ongoing, waiting-for-team

#1299 [THIS-749] 🌐 Set up codecov
  .github/workflows/code-quality.yaml
  .github/workflows/release.yaml
Labels: waiting-for-risk-review

#1298 [THIS-750] 😃 Update CI
  .github/workflows/code-quality.yaml
Labels: risk-review-ongoing, waiting-for-risk-review

#1300 🪦RIP iknow
  .github/CODEOWNERS
Labels: waiting-for-risk-review

#1286 [THIS-736] 🕵 Container pydantic validation
  cognite/neat/_data_model/models/dms/_container.py
  cognite/neat/_utils/validation.py
  tests/tests_unit_v1/test_data_model/test_models/test_dms/test_containers.py
Labels: risk-review-ongoing, waiting-for-risk-review
