Repository cognitedata/neat, pull requests merged in 2025-05, with the labels that each got.

#1087 Neat 880 Selection of base model for sourcing concepts for drop down menus
  cognite/neat/_constants.py
  cognite/neat/_rules/exporters/_rules2excel.py
  cognite/neat/_rules/models/_base_rules.py
  cognite/neat/_session/_template.py
  cognite/neat/_utils/spreadsheet.py
  tests/tests_unit/test_rules/test_exporters/test_rules2excel.py
Labels: risk-review-ongoing, waiting-for-team

#1153 [NEAT-924] 🗒Read Files
  cognite/neat/core/_graph/extractors/_classic_cdf/_files.py
  cognite/neat/session/_read.py
  tests/data/_instances/asset_centric_cdf/files.yaml
  tests/tests_unit/test_graph/test_extractors/test_files_extractor.py
  tests/tests_unit/test_session/test_read.py
Labels: risk-review-ongoing, waiting-for-risk-review

#1170 remove google spreadsheet importer
  cognite/neat/core/_rules/importers/__init__.py
  cognite/neat/core/_rules/importers/_spreadsheet2rules.py
Labels: risk-review-ongoing, waiting-for-team

#1194 ↩Fix reverse issue (#1193)
  cognite/neat/core/_data_model/models/dms/_validation.py
  cognite/neat/core/_issues/warnings/__init__.py
  cognite/neat/core/_issues/warnings/_properties.py
  tests/data/_schema/physical_yamls/reverse_direct_relation_missing_target.expected_issues.yaml
  tests/data/_schema/physical_yamls/reverse_direct_relation_missing_target.yaml
Labels: waiting-for-risk-review

#1168 Refactor YAMLImporter to Dict Importer
  cognite/neat/core/_data_model/importers/__init__.py
  cognite/neat/core/_data_model/importers/_base_file_reader.py
  cognite/neat/core/_data_model/importers/_dict2rules.py
  cognite/neat/core/_data_model/models/mapping/_classic2core.py
  cognite/neat/session/_read.py
  tests/tests_integration/test_api/test_conversion.py
  tests/tests_integration/test_api/test_validate_rules.py
  tests/tests_unit/test_rules/test_exporters/test_rules2yaml.py
Labels: risk-review-ongoing, waiting-for-team

#1163 [NEAT-957] 🏴‍☠️ Statistics endpoint
  cognite/neat/core/_client/_api/statistics.py
  cognite/neat/core/_client/_api_client.py
  cognite/neat/core/_client/data_classes/statistics.py
  cognite/neat/core/_client/testing.py
  tests/tests_integration/test_neat_client/test_statistics.py
Labels: risk-review-ongoing, waiting-for-risk-review

#1165 [NEAT-922] 👷 Fix missing unquote (#1164)
  cognite/neat/core/_instances/transformers/_base.py
  cognite/neat/core/_instances/transformers/_value_type.py
  cognite/neat/core/_utils/rdf_.py
  tests/tests_unit/test_graph/test_transformers/test_connection_to_literal.py
  tests/tests_unit/test_utils/test_rdf.py
Labels: risk-review-ongoing, waiting-for-team

#1216 Session type hint
  cognite/neat/session/exceptions.py
Labels: risk-review-ongoing, waiting-for-risk-review

#1219 Update pyproject.toml with right optional dependency group
  pyproject.toml
  uv.lock
Labels: risk-review-ongoing

#1220 Neat 1007 skip setting node type for instances of system space views
  cognite/neat/core/_instances/loaders/_rdf2dms.py
  tests/tests_integration/test_session/test_graph_flow.py
Labels: risk-review-ongoing, waiting-for-team

#1203 🍒Refactor dms loader
  cognite/neat/core/_instances/loaders/__init__.py
  cognite/neat/core/_instances/loaders/_base.py
  cognite/neat/core/_instances/loaders/_rdf2dms.py
  cognite/neat/core/_instances/loaders/_rdf_to_instance_space.py
  cognite/neat/core/_instances/queries/_select.py
  cognite/neat/session/_to.py
  tests/tests_integration/test_session/test_graph_flow.py
  tests/tests_unit/test_graph/test_loaders/test_dms_loader.py
  tests/tests_unit/test_graph/test_loaders/test_rdf2dms.py
  tests/tests_unit/test_graph/test_loaders/test_rdf_to_instance_space.py
  tests/tests_unit/test_rules/test_importers/test_inference_importer.py
  tests/tests_unit/test_store/test_select_queries.py
Labels: risk-review-ongoing

#1221 rename terminology
  cognite/neat/core/_data_model/importers/_dms2data_model.py
  cognite/neat/core/_data_model/transformers/_converters.py
  cognite/neat/core/_data_model/transformers/_mapping.py
  cognite/neat/core/_data_model/transformers/_verification.py
  cognite/neat/session/_base.py
  cognite/neat/session/_drop.py
  cognite/neat/session/_fix.py
  cognite/neat/session/_mapping.py
  cognite/neat/session/_prepare.py
  cognite/neat/session/_read.py
  cognite/neat/session/_set.py
  cognite/neat/session/_state.py
  cognite/neat/session/_subset.py
  cognite/neat/session/_template.py
  tests/tests_integration/test_session/test_data_model_to.py
Labels: risk-review-ongoing, waiting-for-team
