Repository cognitedata/neat, pull requests merged in 2025-08, with the labels that each got.

#1258 Generic context on Imported Data Model
  cognite/neat/core/_data_model/_shared.py
  cognite/neat/core/_data_model/importers/_dict2data_model.py
  cognite/neat/core/_data_model/importers/_dms2data_model.py
  cognite/neat/core/_data_model/importers/_rdf/_base.py
  cognite/neat/core/_data_model/importers/_spreadsheet2data_model.py
  cognite/neat/core/_data_model/models/_import_contexts.py
  cognite/neat/core/_data_model/models/conceptual/_validation.py
  cognite/neat/core/_data_model/models/physical/_validation.py
  cognite/neat/core/_data_model/transformers/_converters.py
  cognite/neat/core/_issues/_contextmanagers.py
  cognite/neat/core/_issues/_factory.py
  cognite/neat/core/_store/_instance.py
  cognite/neat/core/_utils/auxiliary.py
Labels: risk-review-ongoing, waiting-for-risk-review

#1257 GraphToDataModel importer
  cognite/neat/core/_data_model/importers/__init__.py
  cognite/neat/core/_data_model/importers/_graph2data_model.py
  cognite/neat/core/_data_model/models/_import_contexts.py
  tests/data/_graph/car.py
  tests/data/_schema/conceptual/info-arch-car-rules.xlsx
  tests/data/_schema/physical/car_dms_rules.xlsx
  tests/tests_unit/test_rules/test_importers/test_graph_data_model_importer.py
Labels: risk-review-ongoing, waiting-for-team

#1260 Object oriented NeatSession: Data Model - READ APIs
  cognite/neat/session/_base.py
  cognite/neat/session/_session/__init__.py
  cognite/neat/session/_session/_data_model.py
  tests/tests_end_to_end/test_rules_flow.py
  tests/tests_end_to_end/test_rules_flow/test_excel_importer_to_yaml_new_endpoint.yml
  tests/tests_unit/test_plugins.py
Labels: risk-review-ongoing, risk-review-exemption-big-pr, waiting-for-team

#1264 Add missing CDF reader endpoint
  cognite/neat/session/_session/_data_model/_read.py
  tests/tests_integration/test_session/test_read.py
  tests/tests_integration/test_session/test_read/test_read_cdm.yml
Labels: risk-review-ongoing, waiting-for-team

#1262 Adding write endpoints for neat.data_model
  cognite/neat/core/_utils/auxiliary.py
  cognite/neat/session/_session/_data_model/_routes.py
  cognite/neat/session/_session/_data_model/_write.py
Labels: risk-review-ongoing, waiting-for-team

#1265 trigger warning when redefinition occurs
  cognite/neat/core/_data_model/importers/_rdf/_shared.py
Labels: risk-review-ongoing, waiting-for-team

#1266 Handling of OWL restriction for domain and range
  cognite/neat/core/_data_model/importers/_rdf/_owl2data_model.py
  tests/data/_schema/conceptual/ontology.ttl
  tests/tests_unit/test_rules/test_importers/test_owl_importer.py
Labels: risk-review-ongoing, waiting-for-team

#1271 [THIS-15] 🗽Deferred raising of errors to get correct context.
  cognite/neat/core/_data_model/models/conceptual/_unverified.py
  cognite/neat/core/_data_model/models/entities/_loaders.py
  cognite/neat/core/_data_model/models/physical/_unverified.py
  cognite/neat/core/_issues/errors/_wrapper.py
  tests/data/_schema/physical_invalid/invalid_metadata.xlsx
  tests/tests_unit/test_rules/test_importers/test_excel_importer.py
  tests/tests_unit/test_rules/test_models/test_physical_data_model.py
Labels: risk-review-ongoing, risk-review-mentor, waiting-for-risk-review
