Repository cognitedata/neat, pull requests merged in 2025-06, with the labels that each got.

#1218 [NEAT-1004] 🧑‍🏫 Support index cursorable
  cognite/neat/core/_data_model/_constants.py
  cognite/neat/core/_data_model/importers/_dms2data_model.py
  cognite/neat/core/_data_model/models/entities/__init__.py
  cognite/neat/core/_data_model/models/entities/_single_value.py
  cognite/neat/core/_data_model/models/entities/_types.py
  cognite/neat/core/_data_model/models/physical/_exporter.py
  cognite/neat/core/_data_model/models/physical/_unverified.py
  cognite/neat/core/_data_model/models/physical/_validation.py
  cognite/neat/core/_data_model/models/physical/_verified.py
  docs/artifacts/rules/cdf-dms-architect-alice.xlsx
  docs/excel_data_modeling/physical/properties.md
  tests/tests_integration/test_session/test_graph_flow/test_snapshot_workflow_to_python.yml
  tests/tests_integration/test_session/test_read/test_read_model_referencing_core.yml
  tests/tests_unit/test_rules/test_models/test_entities.py
  tests/tests_unit/test_session/test_flows.py
Labels: risk-review-ongoing, waiting-for-risk-review

#1232 Neat 1030 - Plugin Manager
  cognite/neat/plugins/__init__.py
  cognite/neat/plugins/_issues.py
  cognite/neat/plugins/_manager.py
  cognite/neat/plugins/data_model/__init__.py
  cognite/neat/plugins/data_model/importers/__init__.py
  cognite/neat/plugins/data_model/importers/_base.py
  tests/tests_unit/test_plugins.py
Labels: risk-review-ongoing, waiting-for-team

#1222 [NEAT-958, NEAT-811] Check instance limit
  cognite/neat/core/_client/_api/neat_instances.py
  cognite/neat/core/_constants.py
  cognite/neat/core/_instances/loaders/_rdf2dms.py
  cognite/neat/core/_issues/errors/__init__.py
  cognite/neat/core/_issues/errors/_general.py
  cognite/neat/session/exceptions.py
  tests/tests_unit/test_graph/test_loaders/test_rdf2dms.py
Labels: risk-review-ongoing

#1233 Neat 1031 plugin access via NeatSession
  cognite/neat/plugins/_issues.py
  cognite/neat/plugins/_manager.py
  cognite/neat/plugins/data_model/importers/_base.py
  cognite/neat/session/_base.py
  cognite/neat/session/_experimental.py
  cognite/neat/session/_plugin.py
  cognite/neat/session/exceptions.py
  tests/tests_unit/test_plugins.py
Labels: risk-review-ongoing, waiting-for-team

#1235 Remove DTDL importer
  cognite/neat/core/_data_model/importers/__init__.py
  cognite/neat/core/_data_model/importers/_dtdl2data_model/__init__.py
  cognite/neat/core/_data_model/importers/_dtdl2data_model/_unit_lookup.py
  cognite/neat/core/_data_model/importers/_dtdl2data_model/dtdl_converter.py
  cognite/neat/core/_data_model/importers/_dtdl2data_model/dtdl_importer.py
  cognite/neat/core/_data_model/importers/_dtdl2data_model/spec.py
  tests/data/_schema/non_neat/dtdl/TemperatureController.zip
  tests/data/_schema/non_neat/dtdl/energy-grid/BaseConsumer.json
  tests/data/_schema/non_neat/dtdl/energy-grid/BasePlant.json
  tests/data/_schema/non_neat/dtdl/energy-grid/BaseReceiver.json
  tests/data/_schema/non_neat/dtdl/energy-grid/CityPlant.json
  tests/data/_schema/non_neat/dtdl/energy-grid/CoalPlant.json
  tests/data/_schema/non_neat/dtdl/energy-grid/DeliverySubStation.json
  tests/data/_schema/non_neat/dtdl/energy-grid/DomesticConsumer.json
  tests/data/_schema/non_neat/dtdl/energy-grid/FarmConsumer.json
  tests/data/_schema/non_neat/dtdl/energy-grid/Floor.json
  tests/data/_schema/non_neat/dtdl/energy-grid/GasPlant.json
  tests/data/_schema/non_neat/dtdl/energy-grid/GeneratorSubStation.json
  tests/data/_schema/non_neat/dtdl/energy-grid/HydroPlant.json
  tests/data/_schema/non_neat/dtdl/energy-grid/IndustrialConsumer.json
  tests/data/_schema/non_neat/dtdl/energy-grid/IndustrialPlant.json
  tests/data/_schema/non_neat/dtdl/energy-grid/NuclearPlant.json
  tests/data/_schema/non_neat/dtdl/energy-grid/PowerLine.json
  tests/data/_schema/non_neat/dtdl/energy-grid/Room.json
  tests/data/_schema/non_neat/dtdl/energy-grid/SolarPlant.json
  tests/data/_schema/non_neat/dtdl/energy-grid/Transformer.json
  tests/data/_schema/non_neat/dtdl/energy-grid/WindPlant.json
  tests/tests_unit/test_graph/test_loaders/test_dms_loader.py
  tests/tests_unit/test_rules/test_importers/test_dtdl_importer.py
Labels: risk-review-ongoing, waiting-for-team

#1241 🐛Multiple indices on one property
  cognite/neat/core/_data_model/models/physical/_unverified.py
  cognite/neat/core/_store/_instance.py
  tests/data/_schema/physical_yamls/multiple_indices_on_property.yaml
Labels: risk-review-ongoing

#1242 [NEAT-1115] Unbound local error
  cognite/neat/core/_store/_data_model.py
  tests/tests_unit/test_store/tests_rules_store.py
Labels: waiting-for-risk-review

#1230 [NEAT-1004] 🧑‍🏫Validation of indices
  cognite/neat/core/_data_model/models/physical/_validation.py
  cognite/neat/core/_data_model/models/physical/_verified.py
  cognite/neat/core/_issues/_base.py
  cognite/neat/core/_issues/errors/__init__.py
  cognite/neat/core/_issues/errors/_properties.py
  cognite/neat/core/_issues/warnings/__init__.py
  cognite/neat/core/_issues/warnings/_properties.py
  tests/data/_schema/physical/dm_view_space_different.xlsx
  tests/data/_schema/physical_yamls/invalid_indices.expected_issues.yaml
  tests/data/_schema/physical_yamls/invalid_indices.yaml
  tests/tests_unit/test_rules/test_importers/test_excel_importer.py
Labels: waiting-for-risk-review
