Repository cognitedata/neat, pull requests merged in 2025-10, with the labels that each got.

#1312 [THIS-754] 🤓 As request tests
  tests/tests_unit/test_data_model/test_models/test_dms/test_containers.py
  tests/tests_unit/test_data_model/test_models/test_dms/test_space.py
Labels: risk-review-ongoing, waiting-for-risk-review

#1320 [THIS-762] 🧐MyPy on all tests
  .pre-commit-config.yaml
  pyproject.toml
  tests/tests_data_model/test_models/test_conceptual/test_property.py
  tests/tests_data_model/test_models/test_entities/test_base_entities.py
  tests/tests_data_model/test_models/test_entities/test_data_type.py
  tests/tests_unit/test_data_model/test_models/test_entities/test_identifiers.py
Labels: waiting-for-risk-review

#1306 THIS-268 Add Concept Pydantic Model
  cognite/neat/_data_model/models/conceptual/_concept.py
  cognite/neat/_data_model/models/conceptual/_property.py
  cognite/neat/_data_model/models/entities/_base.py
  cognite/neat/_data_model/models/entities/_constants.py
  tests/tests_data_model/test_models/test_conceptual/test_concept.py
  tests/tests_data_model/test_models/test_conceptual/test_property.py
Labels: risk-review-ongoing, waiting-for-team

#1324 🙃 Remove accelerate team
  .github/CODEOWNERS
Labels: waiting-for-risk-review

#1318 THIS-755 State machine init structure
  cognite/neat/_session/__init__.py
  cognite/neat/_session/_session.py
  cognite/neat/_session/_state_machine/__init__.py
  cognite/neat/_session/_state_machine/_base.py
  cognite/neat/_session/_state_machine/_states.py
  tests/config.py
  tests/data/_misc/state_machine_diagram.md
  tests/data/_misc/state_machine_table.md
  tests/tests_unit/test_session.py
Labels: risk-review-ongoing, waiting-for-team

#1325 [THIS-773] 👷‍♂️ Added fixes to DMS pydantic
  cognite/neat/_data_model/models/dms/__init__.py
  cognite/neat/_data_model/models/dms/_base.py
  cognite/neat/_data_model/models/dms/_constraints.py
  cognite/neat/_data_model/models/dms/_data_types.py
  cognite/neat/_data_model/models/dms/_indexes.py
  cognite/neat/_data_model/models/dms/_types.py
  cognite/neat/_data_model/models/dms/_view_property.py
  tests/tests_unit/test_data_model/test_models/test_dms/strategies.py
  tests/tests_unit/test_data_model/test_models/test_dms/test_containers.py
  tests/tests_unit/test_data_model/test_models/test_dms/test_views.py
Labels: risk-review-ongoing, waiting-for-risk-review
